<a href="https://colab.research.google.com/github/tnphammy/Microsoft-2B-document-intelligence-agent-harness/blob/main/notebooks/phase-1-extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

## Install libraries

In [1]:
import os
import pathlib
import pandas as pd
!pip install pymupdf
!pip install pymupdf4llm
!pip install python-docx
!pip install 'markitdown[all]'

Requirement already satisfied: pymupdf in /usr/local/lib/python3.13/dist-packages (1.28.2)
Requirement already satisfied: pymupdf4llm in /usr/local/lib/python3.13/dist-packages (1.28.2)
Requirement already satisfied: pymupdf==1.28.2 in /usr/local/lib/python3.13/dist-packages (from pymupdf4llm) (1.28.2)
Requirement already satisfied: pymupdf_layout==1.28.2 in /usr/local/lib/python3.13/dist-packages (from pymupdf4llm) (1.28.2)
Requirement already satisfied: tabulate in /usr/local/lib/python3.13/dist-packages (from pymupdf4llm) (0.9.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from pymupdf4llm) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from pymupdf_layout==1.28.2->pymupdf4llm) (6.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pymupdf_layout==1.28.2->pymupdf4llm) (2.1.3)
Requirement already satisfied: onnxruntime in /usr/local/lib/python3.13/dist-packages (from pymupdf_layout==1.28.2->pymupdf4llm) (1.30.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from pymupdf_layout==1.28.2->pymupdf4llm) (3.6.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.13/dist-packages (from onnxruntime->pymupdf_layout==1.28.2->pymupdf4llm) (25.12.19)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from onnxruntime->pymupdf_layout==1.28.2->pymupdf4llm) (26.3)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.13/dist-packages (from onnxruntime->pymupdf_layout==1.28.2->pymupdf4llm) (5.29.6)
Requirement already satisfied: python-docx in /usr/local/lib/python3.13/dist-packages (1.2.0)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from python-docx) (6.1.2)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.13/dist-packages (from python-docx) (4.16.0)
Requirement already satisfied: markitdown[all] in /usr/local/lib/python3.13/dist-packages (0.1.7)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (4.13.5)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (3.4.9)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (0.7.1)
Requirement already satisfied: magika~=0.6.1 in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (0.6.3)
Requirement already satisfied: markdownify in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (1.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (2.32.4)
Requirement already satisfied: azure-ai-contentunderstanding>=1.2.0b1 in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (1.2.0b3)
Requirement already satisfied: azure-ai-documentintelligence in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (1.0.2)
Requirement already satisfied: azure-identity in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (1.25.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (6.1.2)
Requirement already satisfied: mammoth~=1.11.0 in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (1.11.0)
Requirement already satisfied: olefile in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (0.47)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (3.1.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (2.2.3)
Requirement already satisfied: pdfminer-six>=20251230 in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (20260107)
Requirement already satisfied: pdfplumber>=0.11.9 in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (0.11.10)
Requirement already satisfied: pydub in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (0.25.1)
Requirement already satisfied: python-pptx in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (1.0.2)
Requirement already satisfied: speechrecognition in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (3.17.0)
Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (2.0.2)
Requirement already satisfied: youtube-transcript-api~=1.0.0 in /usr/local/lib/python3.13/dist-packages (from markitdown[all]) (1.0.3)
Requirement already satisfied: isodate>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from azure-ai-contentunderstanding>=1.2.0b1->markitdown[all]) (0.7.2)
Requirement already satisfied: azure-core>=1.37.0 in /usr/local/lib/python3.13/dist-packages (from azure-ai-contentunderstanding>=1.2.0b1->markitdown[all]) (1.41.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from azure-ai-contentunderstanding>=1.2.0b1->markitdown[all]) (4.16.0)
Requirement already satisfied: click>=8.1.7 in /usr/local/lib/python3.13/dist-packages (from magika~=0.6.1->markitdown[all]) (8.5.0)
Requirement already satisfied: onnxruntime>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from magika~=0.6.1->markitdown[all]) (1.30.0)
Requirement already satisfied: numpy>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from magika~=0.6.1->markitdown[all]) (2.1.3)
Requirement already satisfied: python-dotenv>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from magika~=0.6.1->markitdown[all]) (1.2.3)
Requirement already satisfied: cobble<0.2,>=0.1.3 in /usr/local/lib/python3.13/dist-packages (from mammoth~=1.11.0->markitdown[all]) (0.1.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer-six>=20251230->markitdown[all]) (50.0.1)
Requirement already satisfied: Pillow>=12.2.0 in /usr/local/lib/python3.13/dist-packages (from pdfplumber>=0.11.9->markitdown[all]) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in /usr/local/lib/python3.13/dist-packages (from pdfplumber>=0.11.9->markitdown[all]) (5.13.0)
Requirement already satisfied: msal>=1.35.1 in /usr/local/lib/python3.13/dist-packages (from azure-identity->markitdown[all]) (1.39.0)
Requirement already satisfied: msal-extensions>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from azure-identity->markitdown[all]) (1.3.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->markitdown[all]) (2.9.2)
Requirement already satisfied: six<2,>=1.15 in /usr/local/lib/python3.13/dist-packages (from markdownify->markitdown[all]) (1.17.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl->markitdown[all]) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->markitdown[all]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->markitdown[all]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->markitdown[all]) (2026.3)
Requirement already satisfied: XlsxWriter>=0.5.7 in /usr/local/lib/python3.13/dist-packages (from python-pptx->markitdown[all]) (3.2.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->markitdown[all]) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->markitdown[all]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->markitdown[all]) (2026.7.22)
Requirement already satisfied: standard-aifc in /usr/local/lib/python3.13/dist-packages (from speechrecognition->markitdown[all]) (3.13.0)
Requirement already satisfied: audioop-lts in /usr/local/lib/python3.13/dist-packages (from speechrecognition->markitdown[all]) (0.2.2)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer-six>=20251230->markitdown[all]) (2.1.1)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from PyJWT[crypto]<3,>=1.0.0->msal>=1.35.1->azure-identity->markitdown[all]) (2.13.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.17.0->magika~=0.6.1->markitdown[all]) (25.12.19)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.17.0->magika~=0.6.1->markitdown[all]) (26.3)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.13/dist-packages (from onnxruntime>=1.17.0->magika~=0.6.1->markitdown[all]) (5.29.6)
Requirement already satisfied: standard-chunk in /usr/local/lib/python3.13/dist-packages (from standard-aifc->speechrecognition->markitdown[all]) (3.13.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer-six>=20251230->markitdown[all]) (3.0)

## Import Data

### Import Files

In [2]:
data_path = '/content/data'

In [3]:
dir_list = os.listdir(data_path)
print("Files and directories in '", data_path, "' :")
# prints all files
print(dir_list)

Files and directories in ' /content/data ' :
['northstar_scholarship_and_financial_aid_guide_2026.pdf', 'northstar_internship_guidelines_2026.docx', 'northstar_student_handbook_and_campus_services_2026.pdf', 'northstar_admissions_and_enrollment_guide_2026.pdf', 'northstar_academic_integrity_policy_2026.pdf', 'northstar_library_services_and_use_rules_2026.pdf', 'northstar_examination_and_grading_policy_2025.pdf', 'northstar_attendance_and_course_participation_policy_2026.docx', 'northstar_laboratory_safety_handbook_2026.docx', 'northstar_examination_and_grading_policy_2026.pdf']

### Sort Files

In [4]:
# Separate list of PDF's and DOCX's
all_pdf = []
all_docx = []

# Sort by PDF and DOCX
for file in dir_list:
  if file.endswith('.pdf'):
    all_pdf.append(file)
  elif file.endswith('.docx'):
    all_docx.append(file)

print(len(all_pdf), " PDFs: ", all_pdf)
print(len(all_docx), " DOCXs: ", all_docx)

7  PDFs:  ['northstar_scholarship_and_financial_aid_guide_2026.pdf', 'northstar_student_handbook_and_campus_services_2026.pdf', 'northstar_admissions_and_enrollment_guide_2026.pdf', 'northstar_academic_integrity_policy_2026.pdf', 'northstar_library_services_and_use_rules_2026.pdf', 'northstar_examination_and_grading_policy_2025.pdf', 'northstar_examination_and_grading_policy_2026.pdf']
3  DOCXs:  ['northstar_internship_guidelines_2026.docx', 'northstar_attendance_and_course_participation_policy_2026.docx', 'northstar_laboratory_safety_handbook_2026.docx']

# Phase 1: Extraction

In [5]:
# Pandas DF to store all extractable information
cols = ["filename", "filepath", "file_type", "md_text", "metadata"]
df = pd.DataFrame(columns=cols)

## PDF's - PyMuPDF

In [6]:
import pymupdf, pymupdf4llm

def extract_pdf_to_entry(pdf:str) -> list:
  """
  Extracts markdown content from pdf file.

  Args:
    pdf: local pdf file

  Returns
    data_entry: a row of information formatted as a list to add to pandas dataframe
  """

  # Get full file path
  file_path = os.path.join(data_path, pdf)

  # Generate markdown
  md_text = pymupdf4llm.to_markdown(file_path)

  # Get metadata
  metadata = pymupdf.open(file_path).metadata

  # Make data entry for this instance in order of: filename, filepath, file_type, md_text, metadata
  data_entry = [pdf, file_path, "pdf", md_text, metadata]

  return data_entry

# Add data_entry as a row in the df
for pdf in all_pdf:
  df.loc[len(df)] = extract_pdf_to_entry(pdf)

display(df.head(7))

=== Document parser messages ===
Using Tesseract for OCR processing.

=== Document parser messages ===
Using Tesseract for OCR processing.

=== Document parser messages ===
Using Tesseract for OCR processing.

=== Document parser messages ===
Using Tesseract for OCR processing.

=== Document parser messages ===
Using Tesseract for OCR processing.

=== Document parser messages ===
Using Tesseract for OCR processing.

=== Document parser messages ===
Using Tesseract for OCR processing.

,filename,filepath,file_type,md_text,metadata
0,northstar_scholarship_and_financial_aid_guide_...,/content/data/northstar_scholarship_and_financ...,pdf,**NORTHSTAR UNIVERSITY** | NSU-AID-2026 \n\n#...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
1,northstar_student_handbook_and_campus_services...,/content/data/northstar_student_handbook_and_c...,pdf,**NORTHSTAR UNIVERSITY** | NSU-STUDENT-2026 \...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
2,northstar_admissions_and_enrollment_guide_2026...,/content/data/northstar_admissions_and_enrollm...,pdf,**NORTHSTAR UNIVERSITY** | NSU-ADMIT-2026 \n\...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
3,northstar_academic_integrity_policy_2026.pdf,/content/data/northstar_academic_integrity_pol...,pdf,**NORTHSTAR UNIVERSITY** | NSU-INTEGRITY-2026...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
4,northstar_library_services_and_use_rules_2026.pdf,/content/data/northstar_library_services_and_u...,pdf,**NORTHSTAR UNIVERSITY** | NSU-LIB-2026 \n\n#...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
5,northstar_examination_and_grading_policy_2025.pdf,/content/data/northstar_examination_and_gradin...,pdf,**NORTHSTAR UNIVERSITY** | NSU-EXAM-2025 \n\n...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
6,northstar_examination_and_grading_policy_2026.pdf,/content/data/northstar_examination_and_gradin...,pdf,**NORTHSTAR UNIVERSITY** | NSU-EXAM-2026 \n\n...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."

## DOCX's - python-docx + MarkItDown

In [7]:
from datetime import datetime
from docx import Document
from markitdown import MarkItDown


# Helper function to reformat python datetime objects to our standard format
def format_date(dt):
    if isinstance(dt, datetime):
        # Formats to a PDF-like date string: D:YYYYMMDDHHMMSS
        return f"D:{dt.strftime('%Y%m%d%H%M%S')}"
    return ""

# Iterate through all DOCX's - fill in DataFrame
def extract_docx_to_entry(docx:str) -> list:
  """
  Extracts markdown content from docx file.

  Args:
    docx: local docx file

  Returns
    data_entry: a row of information formatted as a list to add to pandas dataframe
  """
  # 0. Get full filepath
  file_path = os.path.join(data_path, docx)

  # 1. Get markdown text - MarkItDown
  md = MarkItDown()
  result = md.convert(file_path)
  md_text = result.text_content

  # 2.1. Get metadata - python-docx
  doc = Document(file_path) # Pass file_path here, not docx
  props = doc.core_properties

  # 2.2. Reformat metadata
  metadata = {
      "format": "DOCX",  # Explicit file format
      "title": props.title or "",
      "author": props.author or "",
      "subject": props.subject or "",
      "keywords": props.keywords or "",
      "creator": props.last_modified_by or "",  # Fallback to last modifier
      "producer": "python-docx & Microsoft Word",
      "creationDate": format_date(props.created),
      "modDate": format_date(props.modified),
      "trapped": "",
      "encryption": None,  # docx files aren't encrypted natively this way
  }

  # Make data entry for this instance in order of: filename, filepath, file_type, md_text, metadata
  data_entry = [docx, file_path, "docx", md_text, metadata]

  return data_entry

# Add data_entry as a row in the df
for docx in all_docx:
  df.loc[len(df)] = extract_docx_to_entry(docx)


display(df.tail(3))

,filename,filepath,file_type,md_text,metadata
7,northstar_internship_guidelines_2026.docx,/content/data/northstar_internship_guidelines_...,docx,**Undergraduate Internship Guidelines**\n\n**A...,"{'format': 'DOCX', 'title': 'Undergraduate Int..."
8,northstar_attendance_and_course_participation_...,/content/data/northstar_attendance_and_course_...,docx,**Attendance and Course Participation Policy**...,"{'format': 'DOCX', 'title': 'Attendance and Co..."
9,northstar_laboratory_safety_handbook_2026.docx,/content/data/northstar_laboratory_safety_hand...,docx,**Undergraduate Laboratory Safety Handbook**\n...,"{'format': 'DOCX', 'title': 'Undergraduate Lab..."

In [8]:
# Examine current Dataframe
display(df.head(10))

,filename,filepath,file_type,md_text,metadata
0,northstar_scholarship_and_financial_aid_guide_...,/content/data/northstar_scholarship_and_financ...,pdf,**NORTHSTAR UNIVERSITY** | NSU-AID-2026 \n\n#...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
1,northstar_student_handbook_and_campus_services...,/content/data/northstar_student_handbook_and_c...,pdf,**NORTHSTAR UNIVERSITY** | NSU-STUDENT-2026 \...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
2,northstar_admissions_and_enrollment_guide_2026...,/content/data/northstar_admissions_and_enrollm...,pdf,**NORTHSTAR UNIVERSITY** | NSU-ADMIT-2026 \n\...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
3,northstar_academic_integrity_policy_2026.pdf,/content/data/northstar_academic_integrity_pol...,pdf,**NORTHSTAR UNIVERSITY** | NSU-INTEGRITY-2026...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
4,northstar_library_services_and_use_rules_2026.pdf,/content/data/northstar_library_services_and_u...,pdf,**NORTHSTAR UNIVERSITY** | NSU-LIB-2026 \n\n#...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
5,northstar_examination_and_grading_policy_2025.pdf,/content/data/northstar_examination_and_gradin...,pdf,**NORTHSTAR UNIVERSITY** | NSU-EXAM-2025 \n\n...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
6,northstar_examination_and_grading_policy_2026.pdf,/content/data/northstar_examination_and_gradin...,pdf,**NORTHSTAR UNIVERSITY** | NSU-EXAM-2026 \n\n...,"{'format': 'PDF 1.7', 'title': '', 'author': '..."
7,northstar_internship_guidelines_2026.docx,/content/data/northstar_internship_guidelines_...,docx,**Undergraduate Internship Guidelines**\n\n**A...,"{'format': 'DOCX', 'title': 'Undergraduate Int..."
8,northstar_attendance_and_course_participation_...,/content/data/northstar_attendance_and_course_...,docx,**Attendance and Course Participation Policy**...,"{'format': 'DOCX', 'title': 'Attendance and Co..."
9,northstar_laboratory_safety_handbook_2026.docx,/content/data/northstar_laboratory_safety_hand...,docx,**Undergraduate Laboratory Safety Handbook**\n...,"{'format': 'DOCX', 'title': 'Undergraduate Lab..."

# Phase 2: Chunk Text

# Phase 3: Embeddings

# Phase 4: Depluplication & Verification